### ISSUE TITLE
Create main interface form

### ISSUE THREAD

**Issue by nuffQuantumSayd** [nuffQuantumSayd/AdvancedDotNetTeamProject#2]
this form should have other forms for CRUD functionality

**Comment by sk8kitty** [comment]
List of the forms I need to design:
- [x] MovieManager (main form)
- [x] SeeMovie
- [x] AddMovie
- [x] UpdateMovie
- [x] MoviesWithActor
- [x] ActorManager
- [x] SeeActor
- [x] AddActor
- [x] UpdateActor

*^ I anticipate using a MessageBox instead of a form for deleting, as nothing is being created/changed. It just gets selected from the ListBox and then upon clicking delete the user can be given a "are you sure?" popup and then a "successfully deleted..." popup afterwards.*
<br>  

List of minor things I need to fix:
- [x] Rename the sorting combobox in main form
- [x] Rename the 'manage movie actors' button to BtnMoviesWithActor so it matches the model

**Comment by sk8kitty** [comment]
Last steps for this issue:
- [x] make buttons that open & close forms functional
- [x] comments/exceptions as placeholders for CRUD code (will be helpful)

(this comment was meant to be made hours ago... I left it open and got distracted)
